EventsUI/Models/EventViewModel.cs
using EventsData;
using EventsUI.CustomValidator;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;

namespace EventsUI.Models
{
    public class EventViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime StartDateTime { get; set; }
        public TimeSpan? Duration { get; set; }
        public string Author { get; set; }
        public string Location { get; set; }
        public string Path { get; set; }

        public static Expression<Func<Event, EventViewModel>> ViewModel
        {
            get
            {
                return e => new EventViewModel()
                {
                    Id = e.Id,
                    Title = e.Title,
                    StartDateTime = e.StartDateTime,
                    Duration = e.Duration,
                    Author = e.Author.FullName,
                    Location = e.Location,
                    Path = e.Path,
                };
            }
        }
    }
}

EventsUI/Controllers/EventsController.cs
using EventsData;
using EventsUI.Extensions;
using EventsUI.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventsUI.Controllers
{
    [Authorize]
    public class EventsController : BaseController
    {
        // GET: Events/Create

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EventInputModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                string dbPath = null;
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];
                    string fileName = Path.GetFileNameWithoutExtension(file.FileName);
                    string extention = Path.GetExtension(file.FileName);
                    fileName = "event-" + fileName + extention;
                    dbPath = "/Images/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                    file.SaveAs(fileName);

                }

                var e = new Event()
                {
                    AuthorId = this.User.Identity.GetUserId(),
                    Title = model.Title,
                    StartDateTime = model.StartDateTime,
                    Duration = model.Duration,
                    Description = model.Description,
                    Location = model.Location,
                    IsPublic = model.IsPublic,
                    Path = dbPath,
                };
                this.db.Events.Add(e);
                this.db.SaveChanges();
                this.AddNotification("Event Created", NotificationType.INFO);
                return this.RedirectToAction("My");
            }
            return this.View(model);
        }

        public ActionResult My(int PageNoUpcomming = 1, int PageNoPassed = 1)
        {
            string currentUserId = this.User.Identity.GetUserId();
            var events = this.db.Events
                .Where(e => e.AuthorId == currentUserId)
                .OrderBy(e => e.StartDateTime)
                .Select(EventViewModel.ViewModel);
            var upcomingE = events.Where(e => e.StartDateTime > DateTime.Now);
            var passedE = events.Where(e => e.StartDateTime <= DateTime.Now);
            //pagination upcomming events
            int NoOfUpcommingEPerPage = 6;
            int NoOfUpcommingPages = Convert.ToInt32(Math.Ceiling(Convert.ToDouble(upcomingE.Count()) / Convert.ToDouble(NoOfUpcommingEPerPage)));
            int NoOfUpcommingToSkip = (PageNoUpcomming - 1) * NoOfUpcommingEPerPage;
            ViewBag.PageNoUpcomming = PageNoUpcomming;
            ViewBag.NoOfUpcommingPages = NoOfUpcommingPages;
            var upcommingEvents = upcomingE.Skip(NoOfUpcommingToSkip).Take(NoOfUpcommingEPerPage);


            //pagination passed events
            int NoOfPassedEPerPage = 6;
            int NoOfPassedPages = Convert.ToInt32(Math.Ceiling(Convert.ToDouble(passedE.Count()) / Convert.ToDouble(NoOfPassedEPerPage)));
            int NoOfPassedToSkip = (PageNoPassed - 1) * NoOfPassedEPerPage;
            ViewBag.PageNoPassed = PageNoPassed;
            ViewBag.NoOfPassedPages = NoOfPassedPages;
            var passedEvents = passedE.Skip(NoOfPassedToSkip).Take(NoOfPassedEPerPage);


            return View(new UpcomingPassedEventsViewModel()
            {
                UpcommingEvents = upcommingEvents,
                PassedEvents = passedEvents
            });
        }

        public ActionResult Edit(int id)
        {
            var eventToEdit = this.LoadEvent(id);
            if (eventToEdit == null)
            {
                this.AddNotification("Cannot edit the event #" + id, NotificationType.ERROR);
                return this.RedirectToAction("My");
            }
            var model = EventInputModel.CreateFromEvent(eventToEdit);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, EventInputModel model)
        {
            var eventToEdit = this.LoadEvent(id);
            if (eventToEdit == null)
            {
                this.AddNotification("Cannot edit event #" + id, NotificationType.ERROR);
                return this.RedirectToAction("My");
            }

            if (model != null && ModelState.IsValid)
            {
                eventToEdit.Title = model.Title;
                eventToEdit.StartDateTime = model.StartDateTime;
                eventToEdit.Description = model.Description;
                eventToEdit.Duration = model.Duration;
                eventToEdit.Location = model.Location;
                eventToEdit.IsPublic = model.IsPublic;

                this.db.SaveChanges();
                this.AddNotification("Event edited", NotificationType.INFO);
                return this.RedirectToAction("My");

            }

            return this.View(model);
        }

        public ActionResult Delete(int id)
        {
            var eventToDelete = this.LoadEvent(id);
            if (eventToDelete == null)
            {
                this.AddNotification("Cannot delete the event #" + id, NotificationType.ERROR);
                return this.RedirectToAction("My");
            }
            var model = EventInputModel.CreateFromEvent(eventToDelete);
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id, EventInputModel model)
        {
            var eventToDelete = this.LoadEvent(id);
            if (eventToDelete == null)
            {
                this.AddNotification("Cannot delete the event #" + id, NotificationType.ERROR);
                return this.RedirectToAction("My");
            }
            this.db.Events.Remove(eventToDelete);
            this.db.SaveChanges();
            this.AddNotification("Event deleted", NotificationType.INFO);
            return this.RedirectToAction("My");
        }

        public ActionResult Image(int id)
        {
            Event e = this.db.Events.Where(s => s.Id == id).FirstOrDefault();
            string dbPath = e.Path;
            var indexOfSlash = dbPath.IndexOf("/", 3);
            string fileName = dbPath.Substring(indexOfSlash + 1);
            string filePath = Path.Combine(Server.MapPath("~/Images/"), fileName);
            byte[] filedData = System.IO.File.ReadAllBytes(filePath);
            string contentType = MimeMapping.GetMimeMapping(filePath);
            return File(filedData, contentType, fileName);
        }

        private Event LoadEvent(int id)
        {
            var currentUserId = this.User.Identity.GetUserId();
            var isAdmin = this.IsAdmin();
            var eventToEdit = this.db.Events
                .Where(e => e.Id == id)
                .FirstOrDefault(e => e.AuthorId == currentUserId || isAdmin);
            return eventToEdit;
        }


    }
}

EventsUI/Views/Events/Create.cshtml
@model EventsUI.Models.EventInputModel

@{
    ViewBag.Title = "Create New Event";
}

<h2>@ViewBag.Title</h2>
<hr />

@Html.Partial("_EventEditorForm")

@section scripts {
    @Scripts.Render("~/bundles/bootstrap-datetimepicker")
    @Scripts.Render("~/bundles/jqueryval")
}


@section styles{
    @Styles.Render("~/Content/bootstrap-datetimepicker")
}

EventsUI/Views/Events/Delete.cshtml
@model EventsUI.Models.EventInputModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPublic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPublic)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Cancel", "My", null, htmlAttributes: new { @class = "btn" })
        </div>
    }
</div>

EventsUI/Views/Events/Edit.cshtml
@model EventsUI.Models.EventInputModel
@{
    ViewBag.Title = "Edit Event";
}

<h2>@ViewBag.Title</h2>
<hr />

@Html.Partial("_EventEditorForm")

@section scripts {
    @Scripts.Render("~/bundles/bootstrap-datetimepicker")
    @Scripts.Render("~/bundles/jqueryval")
}

EventsUI/Views/Events/My.cshtml
@model EventsUI.Models.UpcomingPassedEventsViewModel
@{
    ViewBag.Title = "My Events";
}

@Html.Partial("_Events")

@section scripts{
    @Scripts.Render("~/bundles/ajax")
}

EventsUI/Views/Events/_EventEditorForm.cshtml
@model EventsUI.Models.EventInputModel
@using (Html.BeginForm("Create", "Events", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <script>
            $(function () {
                $('#StartDateTime').datetimepicker(
                    {
                        format: 'DD-MMM-YYYY HH:mm',
                        sideBySide: true,
                        showTodayButton: true
                    });
            });
        </script>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <script>
            $(function () {
                var date = new Date();
                date.setHours(1);
                date.setMinutes(0);
                $('#Duration').datetimepicker(
                    {
                        format: 'HH:mm',
                        defaultDate: date,
                        showClear: true
                    });
            });
        </script>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="col-md-10">
                    <input type="file" name="Img" />
                    @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPublic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.IsPublic, htmlAttributes: new { @checked = "true" })
                @Html.ValidationMessageFor(model => model.IsPublic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                @Html.ActionLink("Cancel", "My", null, htmlAttributes: new { @class = "btn" })
            </div>
        </div>
    </div>
}